MC44PST7 ;ALB/JAM - MEDICAL DIAGNOSES UPDATE WITH ICD10 CODES ;3/26/12  15:45
 ;;2.3;Medicine;**44**;09/13/1996;Build 9
 ;
 ;CALLED FROM MC44PST0
 Q
CODES ;
 ;;MELANOSIS COLI NOTED^K63.4
 ;;MELANOSIS COLI NOTED^K63.89
 ;;MELANOSIS COLI NOTED^K92.89
 ;;SEGMENTAL COLITIS NOTED^K50.10
 ;;SEGMENTAL COLITIS NOTED^K50.111
 ;;SEGMENTAL COLITIS NOTED^K50.112
 ;;SEGMENTAL COLITIS NOTED^K50.113
 ;;SEGMENTAL COLITIS NOTED^K50.114
 ;;SEGMENTAL COLITIS NOTED^K50.118
 ;;SEGMENTAL COLITIS NOTED^K50.119
 ;;SCLEROSING CHOLANGITIS DETECTED^K80.30
 ;;SCLEROSING CHOLANGITIS DETECTED^K80.31
 ;;SCLEROSING CHOLANGITIS DETECTED^K80.32
 ;;SCLEROSING CHOLANGITIS DETECTED^K80.33
 ;;SCLEROSING CHOLANGITIS DETECTED^K80.34
 ;;SCLEROSING CHOLANGITIS DETECTED^K80.35
 ;;SCLEROSING CHOLANGITIS DETECTED^K80.36
 ;;SCLEROSING CHOLANGITIS DETECTED^K80.37
 ;;SCLEROSING CHOLANGITIS DETECTED^K83.0
 ;;CHRONIC PANCREATITIS FOUND^K86.0
 ;;CHRONIC PANCREATITIS FOUND^K86.1
 ;;ANNULAR PANCREAS IDENTIFIED^Q45.0
 ;;ANNULAR PANCREAS IDENTIFIED^Q45.1
 ;;ANNULAR PANCREAS IDENTIFIED^Q45.2
 ;;ANNULAR PANCREAS IDENTIFIED^Q45.3
 ;;METASTATIC CARCINOMA SUSPECTED^C45.9
 ;;METASTATIC CARCINOMA SUSPECTED^C80.1
 ;;METASTATIC CARCINOMA SUSPECTED^D09.9 
 ;;MIGRATION OF STENT NOTED^Z96.21
 ;;MIGRATION OF STENT NOTED^Z96.22
 ;;MIGRATION OF STENT NOTED^Z97.4
 ;;MIGRATION OF STENT NOTED^Z97.8
 ;;MIGRATION OF STENT NOTED^Z98.3
 ;;MIGRATION OF STENT NOTED^Z98.62
 ;;MIGRATION OF STENT NOTED^Z98.89
 ;;HEMATOBILIA OBSERVED^K83.5
 ;;HEMATOBILIA OBSERVED^K83.8
 ;;HEMATOBILIA OBSERVED^K87.
 ;;CHOLELITHIASIS OBSERVED^K80.20
 ;;CHOLELITHIASIS OBSERVED^K80.80
 ;;MALROTATION ANOMALY NOTED^Q89.9
 ;;BENIGN APPEARING STENOSIS NOTED^K31.1
 ;;COMMON DUCT STONE IMPACTION ENCOUNTERED^K56.49
 ;;BENIGN APPEARING ULCER FOUND^K25.0
 ;;BENIGN APPEARING ULCER FOUND^K63.3
 ;;MALIGNANT APPEARING ULCER FOUND^C16.9
 ;;MALIGNANT APPEARING ULCER FOUND^D00.2
 ;;MALIGNANT APPEARING ULCER FOUND^C78.7
 ;;MALIGNANT APPEARING ULCER FOUND^C78.80
 ;;MALIGNANT APPEARING ULCER FOUND^C78.89
 ;;BLEEDING DIVERTICULUM FOUND^K22.5
 ;;BLEEDING DIVERTICULUM FOUND^K57.10
 ;;BLEEDING DIVERTICULUM FOUND^K57.50
 ;;BLEEDING DIVERTICULUM FOUND^Q43.0
 ;;BLEEDING DIVERTICULUM FOUND^K31.4
 ;;DOUBLE DUCT SIGN OF PANCREATIC CARCINOMA SEEN^K86.1
 ;;DOUBLE DUCT SIGN OF PANCREATIC CARCINOMA SEEN^K86.8
 ;;DOUBLE DUCT SIGN OF PANCREATIC CARCINOMA SEEN^K87.
 ;;NORMAL ERCP PERFORMED^Z71.1
 ;;NORMAL ENDOSCOPY AND BILIARY TREE FOUND^Z71.1
 ;;NORMAL ENDOSCOPY AND PANCREATIC DUCT FOUND^Z71.1
 ;;NORMAL GALLBLADDER AND CYSTIC DUCT FOUND^Z71.1
 ;;CHOLEDOCHOLITHIASIS VISUALIZED^K80.30
 ;;CHOLEDOCHOLITHIASIS VISUALIZED^K80.32
 ;;CHOLEDOCHOLITHIASIS VISUALIZED^K80.34
 ;;CHOLEDOCHOLITHIASIS VISUALIZED^K80.36
 ;;CHOLEDOCHOLITHIASIS VISUALIZED^K80.50
 ;;PAPILLARY STENOSIS FOUND^K83.1
 ;;BILIARY DYSKINESIA ENCOUNTERED^K91.5
 ;;CANCER OF BILE DUCT FOUND^C22.0
 ;;CANCER OF BILE DUCT FOUND^C22.2
 ;;CANCER OF BILE DUCT FOUND^C22.3
 ;;CANCER OF BILE DUCT FOUND^C22.4
 ;;CANCER OF BILE DUCT FOUND^C22.7
 ;;CANCER OF BILE DUCT FOUND^C22.8
 ;;CHOLEDOCHOCELE FOUND^K80.30
 ;;CHOLEDOCHOCELE FOUND^K80.31
 ;;CHOLEDOCHOCELE FOUND^K80.32
 ;;CHOLEDOCHOCELE FOUND^K80.33
 ;;CHOLEDOCHOCELE FOUND^K80.34
 ;;CHOLEDOCHOCELE FOUND^K80.35
 ;;CHOLEDOCHOCELE FOUND^K80.36
 ;;CHOLEDOCHOCELE FOUND^K80.37
 ;;CHOLEDOCHOCELE FOUND^K83.0
 ;;CHOLEDOCHO CYST FOUND^K83.9
 ;;GALLSTONE PANCREATITIS SUSPECTED^B25.2
 ;;GALLSTONE PANCREATITIS SUSPECTED^K85.0
 ;;GALLSTONE PANCREATITIS SUSPECTED^K85.1
 ;;GALLSTONE PANCREATITIS SUSPECTED^K85.2
 ;;GALLSTONE PANCREATITIS SUSPECTED^K85.3
 ;;GALLSTONE PANCREATITIS SUSPECTED^K85.8
 ;;GALLSTONE PANCREATITIS SUSPECTED^K85.9
 ;;GALLSTONE PANCREATITIS SUSPECTED^K86.0
 ;;GALLSTONE PANCREATITIS SUSPECTED^K86.1
 ;;CARCINOMA OF PANCREATIC HEAD SUSPECTED^C25.0
 ;;CARCINOMA OF PANCREATIC BODY SUSPECTED^C25.0
 ;;CARCINOMA OF PANCREATIC TAIL SUSPECTED^C25.0
 ;;STRICTURE OF BILE DUCT OBSERVED^K83.1
 ;;STRICTURE OF PANCREATIC DUCT OBSERVED^K83.1
 ;;PSEUDOCYST OF PANCREATIC HEAD FOUND^K86.2
 ;;PSEUDOCYST OF PANCREATIC HEAD FOUND^K86.3
 ;;PSEUDOCYST OF PANCREATIC BODY FOUND^K86.2
 ;;PSEUDOCYST OF PANCREATIC BODY FOUND^K86.3
 ;;PSEUDOCYST OF PANCREATIC TAIL FOUND^K86.2
 ;;PSEUDOCYST OF PANCREATIC TAIL FOUND^K86.3
 ;;PANCREAS DIVIISUM FOUND^K86.1
 ;;PANCREAS DIVIISUM FOUND^K86.8
 ;;PANCREAS DIVIISUM FOUND^K87.
 ;;ACUTE PANCREATITIS SUSPECTED^B25.2
 ;;ACUTE PANCREATITIS SUSPECTED^K85.0
 ;;ACUTE PANCREATITIS SUSPECTED^K85.1
 ;;ACUTE PANCREATITIS SUSPECTED^K85.2
 ;;ACUTE PANCREATITIS SUSPECTED^K85.3
 ;;ACUTE PANCREATITIS SUSPECTED^K85.8
 ;;ACUTE PANCREATITIS SUSPECTED^K85.9
 ;;ASCENDING CHOLANGITIS FOUND^K80.30
 ;;ASCENDING CHOLANGITIS FOUND^K80.31
 ;;ASCENDING CHOLANGITIS FOUND^K80.32
 ;;ASCENDING CHOLANGITIS FOUND^K80.33
 ;;ASCENDING CHOLANGITIS FOUND^K80.34
 ;;ASCENDING CHOLANGITIS FOUND^K80.35
 ;;ASCENDING CHOLANGITIS FOUND^K80.36
 ;;ASCENDING CHOLANGITIS FOUND^K80.37
 ;;ASCENDING CHOLANGITIS FOUND^K83.0
 ;;PRIOR ENDOSCOPIC SPHINCTEROTOMY INCISION SEEN^Z96.21
 ;;PRIOR ENDOSCOPIC SPHINCTEROTOMY INCISION SEEN^Z96.22
 ;;PRIOR ENDOSCOPIC SPHINCTEROTOMY INCISION SEEN^Z97.4
 ;;PRIOR ENDOSCOPIC SPHINCTEROTOMY INCISION SEEN^Z97.8
 ;;PRIOR ENDOSCOPIC SPHINCTEROTOMY INCISION SEEN^Z98.3
 ;;PRIOR ENDOSCOPIC SPHINCTEROTOMY INCISION SEEN^Z98.62
 ;;PRIOR ENDOSCOPIC SPHINCTEROTOMY INCISION SEEN^Z98.89
 ;;POST CHOLECYSTECTOMY STATUS FOUND^Z96.21
 ;;POST CHOLECYSTECTOMY STATUS FOUND^Z96.22
 ;;POST CHOLECYSTECTOMY STATUS FOUND^Z97.4
 ;;POST CHOLECYSTECTOMY STATUS FOUND^Z97.8
 ;;POST CHOLECYSTECTOMY STATUS FOUND^Z98.3
 ;;POST CHOLECYSTECTOMY STATUS FOUND^Z98.62
 ;;POST CHOLECYSTECTOMY STATUS FOUND^Z98.89
 ;;MICRO GALLBLADDER SEEN^K82.9
 ;;STONE(S) FOUND IN PANCREATIC DUCT^K86.1
 ;;STONE(S) FOUND IN PANCREATIC DUCT^K86.8
 ;;STONE(S) FOUND IN PANCREATIC DUCT^K87.
 ;;NORMAL DORSAL PANCREATIC DUCT^Z71.1
 ;;STRICTURE POST COMMON DUCT EXPLORATION FOUND^K83.1
 ;;RECURRENT PANCREATITIS SEEN^K86.0
 ;;RECURRENT PANCREATITIS SEEN^K86.1
 ;;BILIARY STRICTURE IDENTIFIED^K91.5
 ;;COMMON BILE DUCT STRICTURE SEEN^K83.1
 ;;COMMON BILE DUCT STRICTURE SEEN^Q44.2
 ;;COMMON BILE DUCT STRICTURE SEEN^Q44.3
 ;;COMMON BILE DUCT STONES CONFIRMED^K80.20
 ;;COMMON BILE DUCT STONES CONFIRMED^K80.80
 ;;HISTORY OF TRAUMATIC PANCREATITIS^K86.0
 ;;HISTORY OF TRAUMATIC PANCREATITIS^K86.1
 ;;NORMAL PANCREATIC DUCT FOUND^Z71.1
 ;;NORMAL SPHINCTER OF ODDI MANOMETRY RECORDED^Z71.1
 ;;NORMAL ENDOSCOPIC EXAMINATION^Z71.1
 ;;PANCREATIC TUMOR SUSPECTED^D13.6
 ;;PANCREATIC TUMOR SUSPECTED^K86.9
 ;;POSSIBLE PAPILLARY STENOSIS^K83.1
 ;;POST SURGICAL SPHINCTEROTOMY STATUS^Z96.21
 ;;POST SURGICAL SPHINCTEROTOMY STATUS^Z96.22
 ;;POST SURGICAL SPHINCTEROTOMY STATUS^Z97.4
 ;;POST SURGICAL SPHINCTEROTOMY STATUS^Z97.8
 ;;POST SURGICAL SPHINCTEROTOMY STATUS^Z98.3
 ;;POST SURGICAL SPHINCTEROTOMY STATUS^Z98.62
 ;;POST SURGICAL SPHINCTEROTOMY STATUS^Z98.89
 ;;DILATED PANCREATIC DUCT VISUALIZED^K86.1
 ;;DILATED PANCREATIC DUCT VISUALIZED^K86.8
 ;;DILATED PANCREATIC DUCT VISUALIZED^K87.
 ;;CHOLEDOCHODUODENAL FISTULA SEEN^K83.3
 ;;TACHYODDIA OF COMMON BILE DUCT FOUND^Q44.1
 ;;TACHYODDIA OF COMMON BILE DUCT FOUND^Q44.5
 ;;TACHYODDIA OF COMMON BILE DUCT FOUND^Q44.7
 ;;DILATED COMMON BILE DUCT VISUALIZED^Q44.0
 ;;DILATED COMMON BILE DUCT VISUALIZED^Q44.1
 ;;DILATED COMMON BILE DUCT VISUALIZED^Q44.4
 ;;DILATED COMMON BILE DUCT VISUALIZED^Q44.5
 ;;DILATED COMMON BILE DUCT VISUALIZED^Q44.7
 ;;DILATED COMMON BILE DUCT VISUALIZED^K83.5
 ;;DILATED COMMON BILE DUCT VISUALIZED^K83.8
 ;;DILATED COMMON BILE DUCT VISUALIZED^K87.
 ;;DILATED COMMON BILE DUCT VISUALIZED^K80.30
 ;;DILATED COMMON BILE DUCT VISUALIZED^K80.32
 ;;DILATED COMMON BILE DUCT VISUALIZED^K80.34
 ;;DILATED COMMON BILE DUCT VISUALIZED^K80.36
 ;;DILATED COMMON BILE DUCT VISUALIZED^K80.50
 ;;DILATED GALL BLADDER SEEN^K82.8
 ;;DILATED GALL BLADDER SEEN^Q44.0
 ;;DILATED GALL BLADDER SEEN^Q44.1
 ;;DILATED GALL BLADDER SEEN^Q44.4
 ;;DILATED GALL BLADDER SEEN^Q44.5
 ;;DILATED GALL BLADDER SEEN^Q44.7
 ;;COMMON DUCT EXTERNALLY COMPRESSED^S36.122A
 ;;COMMON DUCT EXTERNALLY COMPRESSED^S36.123A
 ;;COMMON DUCT EXTERNALLY COMPRESSED^S36.128A
 ;;COMMON DUCT EXTERNALLY COMPRESSED^S36.129A
 ;;COMMON DUCT EXTERNALLY COMPRESSED^S36.13xA
 ;;GALLBLADDER STONES IDENTIFIED^N21.0
