DVBAPL9 ;ALB/CMM LONG DESCRIPTION FOR FILE 31 UPDATE ;2/2/94
 ;;2.7;AMIE;;Apr 10, 1995
 ;
 ;Format is Exam Number ; Long Description
 ;
EN ;
 ;;5202;HUMERUS, OTHER IMPAIRMENT OF
 ;;5203;CLAVICLE OR SCAPULA, IMPAIRMENT OF
 ;;5209;ELBOW, OTHER IMPAIRMENT OF FLAIL JOINT
 ;;5210;RADIUS AND ULNA, NONUNION OF, WITH FLAIL FALSE JOINT
 ;;5211;ULNA, IMPAIRMENT OF
 ;;5212;RADIUS, IMPAIRMENT OF
 ;;5255;FEMUR, IMPAIRMENT OF
 ;;5276;FLATFOOT, ACQUIRED
 ;;5277;WEAK FOOT, BILATERAL
 ;;5278;CLAW FOOT (PES CAVUS), ACQUIRED
 ;;5279;METATARSALGIA, ANTERIOR (MORTON'S DISEASE), UNILATERAL OR BILATERAL
 ;;5280;HALLUX VALGUS, UNILATERAL
 ;;5281;HALLUX RIGIDUS, UNILATERAL, SEVERE
 ;;5282;HAMMER TOE
 ;;5283;TARSAL OR METATARSAL BONES, MALUNION OF, OR NONUNION OF
 ;;5284;FOOT INJURIES, OTHER
 ;;5105;ANATOMICAL LOSS OF ONE FOOT AND LOSS OF USE OF ONE HAND
 ;;5109;LOSS OF USE OF BOTH HANDS
 ;;5111;LOSS OF USE OF ONE HAND AND ONE FOOT
 ;;5216;FIVE DIGITS OF ONE HAND, UNFAVORABLE ANKYLOSIS OF
 ;;5217;FOUR DIGITS OF ONE HAND, UNFAVORABLE ANKYLOSIS OF
 ;;5218;THREE DIGITS OF ONE HAND, UNFAVORABLE ANKYLOSIS OF
 ;;5219;TWO DIGITS OF ONE HAND, UNFAVORABLE ANKYLOSIS OF
 ;;5220;FIVE DIGITS OF ONE HAND, FAVORABLE ANKYLOSIS OF
 ;;5221;FOUR DIGITS OF ONE HAND, FAVORABLE ANKYLOSIS OF
 ;;5222;THREE DIGITS OF ONE HAND, FAVORABLE ANKYLOSIS
 ;;5223;TWO DIGITS OF ONE HAND, FAVORABLE ANKYLOSIS OF
 ;;5224;ANKYLOSIS OF THUMB
 ;;5225;ANKYLOSIS OF INDEX FINGER
 ;;5226;ANKYLOSIS OF MIDDLE FINGER
 ;;5227;ANKYLOSIS OF ANY OTHER FINGER
 ;;5054;HIP REPLACEMENT (PROSTHESIS)
 ;;5250;ANKYLOSIS OF HIP
 ;;5251;THIGH, LIMITATION OF EXTENSION OF
 ;;5252;THIGH, LIMITATION OF FLEXION OF
 ;;5253;THIGH, IMPAIRMENT OF
 ;;5254;HIP, FLAIL JOINT
 ;;5255;FEMUR, IMPAIRMENT OF
