PXRMDHLP ; SLC/PJH - Reminder dialog main help. ;07/02/2002
 ;;2.0;CLINICAL REMINDERS;;Feb 04, 2005
 ;
 ; Entry action for list PXRM DIALOG MAIN HELP 
 ;
LOAD N DONE,IND,TEXT
 S DONE=0
 K ^TMP("PXRMDHLP",$J)
 S VALMCNT=0
 F IND=1:1 Q:DONE  D
 . S TEXT=$P($T(@PXRMTAG+IND),";",3)
 . I TEXT="**End Text**" S DONE=1 Q
 . S VALMCNT=VALMCNT+1
 . S ^TMP("PXRMDHLP",$J,VALMCNT,0)=TEXT
 S ^TMP("PXRMDHLP",$J,"VALMCNT")=VALMCNT
 Q
 ;
RCAT ;Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    Display, edit, delete or print a reminder category.
 ;;
 ;;AD  Add
 ;;    Add a new reminder category.
 ;;
 ;;PT  List Categories
 ;;    Print a list of all the reminder categories defined in the
 ;;    current UCI.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
DLG ;Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    Display, edit, delete or print a reminder dialog.
 ;;
 ;;AD  Add
 ;;    Add a new REMINDER DIALOG. The dialog may be either autogenerated
 ;;    from the dialog definition or input manually.
 ;;
 ;;CV  Change View
 ;;    The initial display is of reminder dialogs only. This may be
 ;;    changed to display:
 ;;          
 ;;    additional prompts, forced values, dialog elements,
 ;;    dialog groups, result groups or result elements.
 ;;  
 ;;    A display by reminder may also be selected. 
 ;;
 ;;PT  List
 ;;    Print a list of all the reminder dialogs that are defined in the
 ;;    current UCI.
 ;;
 ;;RN  Name/Print Name
 ;;    Toggle reminder name and reminder print name.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
DLGE ;Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    Display, edit, delete or print a dialog.
 ;;
 ;;AD  Add
 ;;    Add a new dialog. Elements or Groups may be created.
 ;;
 ;;CO  Copy Dialog
 ;;    Copy a selected dialog to a new name.
 ;;
 ;;CV  Change View
 ;;    Change display to a different dialog type:
 ;;      
 ;;    dialog elements, additional prompts, forced values,
 ;;    dialog groups, result groups, result elements or 
 ;;    reminder dialogs. 
 ;;
 ;;    A display by reminder may also be selected. 
 ;;
 ;;INQ Inquiry/Print
 ;;    Print details for a selected dialog.
 ;;    (restricted to dialog type in the current view)
 ;;    
 ;;PT  List All
 ;;    Print a list of all dialogs of this type defined in the current
 ;;    UCI.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
DLGR ;Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    Select reminder to view dialogs for the reminder.
 ;;
 ;;AR  All Reminders
 ;;    View all reminders.
 ;;
 ;;CV  Change View
 ;;    The initial display is of reminders in name order. This may be
 ;;    changed to a display of:
 ;;          
 ;;    reminder dialogs, additional prompts, forced values,
 ;;    dialog groups, dialog elements, result groups or result elements.
 ;;
 ;;LR  Linked Reminders
 ;;    View only reminders linked to dialogs.
 ;;
 ;;RN  Name/Print Name
 ;;    Toggle reminder name and reminder print name.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
DTAX ;Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    Display, edit or print dialog for this taxonomy.
 ;;
 ;;PT  List All
 ;;    Print a list of all taxonomy dialogs defined in the
 ;;    current UCI.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
RESN ;Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    Display, edit or print a reminder resolution.
 ;;
 ;;AD  Add
 ;;    Add a new LOCAL reminder resolution.
 ;;
 ;;PT  List All
 ;;    Print a list of all the reminder resolutions defined in the
 ;;    current UCI.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
SHFR ;Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    Display, edit or print a health factor resolution.
 ;;
 ;;AD  Add
 ;;    Add a new health factor resolution or select a reminder and
 ;;    add or modify resolution statuses for each health factor finding
 ;;    on the reminder. 
 ;;
 ;;PT  List All
 ;;    Print a list of all health factor resolutions defined in the
 ;;    current UCI.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
FIP ;Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    Display, edit or print a finding item parameter.
 ;;
 ;;AD  Add
 ;;    Add a new finding item parameter.
 ;;
 ;;PT  List All
 ;;    Print a list of all finding item parameters defined in the
 ;;    current UCI.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
FPAR ;Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    Display, edit or print parameters for this finding type.
 ;;
 ;;PT  List All
 ;;    Print a list of all finding type parameters defined in the
 ;;    current UCI.
 ;;
 ;;QU  Quit
 ;;**End Text**
 Q
 ;
GRCAT ;General Help text
 ;;The following actions are available:
 ;;
 ;;ED  Edit
 ;;    Edit or delete this reminder category.
 ;;
 ;;INQ Inquiry/Print
 ;;    Print details of this reminder category.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
GDLG ;General Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Item
 ;;    To copy, edit or delete a component in this dialog.
 ;;
 ;;ADD Add Element/Group
 ;;    Allows a dialog element or dialog group to be added to the
 ;;    reminder dialog.
 ;;
 ;;CO  Copy Dialog
 ;;    Copy this reminder dialog to a new name.
 ;;
 ;;DD  Detailed Display
 ;;    Display dialog element names and resolution detail for this
 ;;    reminder dialog.
 ;;
 ;;DP  Progress Note Text
 ;;    Display text that will be entered in the progress note.
 ;;
 ;;DS  Dialog Summary (default)
 ;;    Display dialog element names.
 ;;
 ;;D0  Dialog Overview
 ;;    Display the top-level dialog groups/elements. This option will
 ;;    not display any nested dialog elements or group.
 ;;
 ;;DT  Dialog Text
 ;;    Display the dialog text as it should appear in CPRS.
 ;;
 ;;ED  Edit/Delete Dialog
 ;;    Edit or delete this reminder dialog. Allows addition and deletion
 ;;    of existing dialog elements from this reminder dialog. Allows the
 ;;    sequence numbers to be changed. Also enable/disable dialog.
 ;;
 ;;INQ Inquiry/Print (for Reminder Dialogs only)
 ;;    Print details of this reminder dialog.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;;
GDLGH ;General Help text
 ;;The following actions are available:
 ;;
 ;;AD  Autogenerate Dialog
 ;;    Generate a reminder dialog for the current reminder.
 ;;
 ;;LR  Link Reminder
 ;;    Link the current reminder to a reminder dialog.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;;
GDTAX ;General Help text
 ;;The following actions are available:
 ;;
 ;;ED  Edit
 ;;    Edit taxonomy dialog fields.
 ;;
 ;;INQ Inquiry/Print
 ;;    Print details of dialog for the taxonomy.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
GRESN ;General Help text
 ;;The following actions are available:
 ;;
 ;;ED  Edit
 ;;    Edit or delete this resolution status.
 ;;
 ;;INQ Inquiry/Print
 ;;    Print details of this resolution status.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
GSHFR ;General Help text
 ;;The following actions are available:
 ;;
 ;;ED  Edit
 ;;    Edit or delete the resolution status(s) for this health factor.
 ;;
 ;;INQ Inquiry/Print
 ;;    Print details of this health factor's resolution statuses.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
GFIP ;General Help text
 ;;The following actions are available:
 ;;
 ;;ED  Edit
 ;;    Edit or delete this finding item parameter.
 ;;
 ;;INQ Inquiry/Print
 ;;    Print details of this finding item parameter.
 ;;
 ;;QU  Quit
 ;;**End Text**
 ;
GFPAR ;General Help text
 ;;The following actions are available:
 ;;
 ;;#   Select Resolution Status to edit
 ;;    Disable/Enable the selected resolution status or modify the
 ;;    prefix and suffix text.
 ;;
 ;;INQ Inquiry/Print
 ;;    Print details of this finding parameter.
 ;;
 ;;QU  Quit
 ;;**End Text**
 Q
