ACKQTE9 ; ;11/10/10
 D DE G BEGIN
DE S DIE="^ACK(509850.6,D0,3,",DIC=DIE,DP=509850.61,DL=2,DIEL=1,DU="" K DG,DE,DB Q:$O(^ACK(509850.6,D0,3,DA,""))=""
 I $D(^(0)) S %Z=^(0) S %=$P(%Z,U,1) S:%]"" DE(1)=% S %=$P(%Z,U,3) S:%]"" DE(6)=% S %=$P(%Z,U,4) S:%]"" DE(8)=%
 K %Z Q
 ;
W W !?DL+DL-2,DLB_": "
 Q
O D W W Y W:$X>45 !?9
 I $L(Y)>19,'DV,DV'["I",(DV["F"!(DV["K")) G RW^DIR2
 W:Y]"" "// " I 'DV,DV["I",$D(DE(DQ))#2 S X="" W "  (No Editing)" Q
TR R X:DTIME E  S (DTOUT,X)=U W $C(7)
 Q
A K DQ(DQ) S DQ=DQ+1
B G @DQ
RE G PR:$D(DE(DQ)) D W,TR
N I X="" G NKEY:$D(^DD("KEY","F",DP,DIFLD)),A:DV'["R",X:'DV,X:D'>0,A
RD G QS:X?."?" I X["^" D D G ^DIE17
 I X="@" D D G Z^DIE2
 I X=" ",DV["d",DV'["P",$D(^DISV(DUZ,"DIE",DLB)) S X=^(DLB) I DV'["D",DV'["S" W "  "_X
T G M^DIE17:DV,^DIE3:DV["V",P:DV'["S" X:$D(^DD(DP,DIFLD,12.1)) ^(12.1) I X?.ANP D SET I 'DDER X:$D(DIC("S")) DIC("S") I  W:'$D(DB(DQ)) "  "_% G V
 K DDER G X
P I DV["P" S DIC=U_DU,DIC(0)=$E("EN",$D(DB(DQ))+1)_"M"_$E("L",DV'["'") S:DIC(0)["L" DLAYGO=+$P(DV,"P",2) G:DV["*" AST^DIED D NOSCR^DIED S X=+Y,DIC=DIE G X:X<0
 G V:DV'["N" D D I $L($P(X,"."))>24 K X G Z
 I $P(DQ(DQ),U,5)'["$",X?.1"-".N.1".".N,$P(DQ(DQ),U,5,99)["+X'=X" S X=+X
V D @("X"_DQ) K YS
Z K DIC("S"),DLAYGO I $D(X),X'=U D:$G(DE(DW,"INDEX")) SAVEVALS G:'$$KEYCHK UNIQFERR^DIE17 S DG(DW)=X S:DV["d" ^DISV(DUZ,"DIE",DLB)=X G A
X W:'$D(ZTQUEUED) $C(7),"??" I $D(DB(DQ)) G Z^DIE17
 S X="?BAD"
QS S DZ=X D D,QQ^DIEQ G B
D S D=DIFLD,DQ(DQ)=DLB_U_DV_U_DU_U_DW_U_$P($T(@("X"_DQ))," ",2,99) Q
Y I '$D(DE(DQ)) D O G RD:"@"'[X,A:DV'["R"&(X="@"),X:X="@" S X=Y G N
PR S DG=DV,Y=DE(DQ),X=DU I $D(DQ(DQ,2)) X DQ(DQ,2) G RP
R I DG["P",@("$D(^"_X_"0))") S X=+$P(^(0),U,2) G RP:'$D(^(Y,0)) S Y=$P(^(0),U),X=$P(^DD(X,.01,0),U,3),DG=$P(^(0),U,2) G R
 I DG["V",+Y,$P(Y,";",2)["(",$D(@(U_$P(Y,";",2)_"0)")) S X=+$P(^(0),U,2) G RP:'$D(^(+Y,0)) S Y=$P(^(0),U) I $D(^DD(+X,.01,0)) S DG=$P(^(0),U,2),X=$P(^(0),U,3) G R
 X:DG["D" ^DD("DD") I DG["S" S %=$P($P(";"_X,";"_Y_":",2),";") S:%]"" Y=%
RP D O I X="" S X=DE(DQ) G A:'DV,A:DC<2,N^DIE17
I I DV'["I",DV'["#" G RD
 D E^DIE0 G RD:$D(X),PR
 Q
SET N DIR S DIR(0)="SV"_$E("o",$D(DB(DQ)))_U_DU,DIR("V")=1
 I $D(DB(DQ)),'$D(DIQUIET) N DIQUIET S DIQUIET=1
 D ^DIR I 'DDER S %=Y(0),X=Y
 Q
SAVEVALS S @DIEZTMP@("V",DP,DIIENS,DIFLD,"O")=$G(DE(DQ)) S:$D(^("F"))[0 ^("F")=$G(DE(DQ))
 I $D(DE(DW,"4/")) S @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")=""
 E  K @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")
 Q
NKEY W:'$D(ZTQUEUED) "??  Required key field" S X="?BAD" G QS
KEYCHK() Q:$G(DE(DW,"KEY"))="" 1 Q @DE(DW,"KEY")
BEGIN S DNM="ACKQTE9",DQ=1+D G B
1 S DW="0;1",DV="M*P509850.4'X",DU="",DLB="PROCEDURE CODE",DIFLD=.01
 S DE(DW)="C1^ACKQTE9"
 S DU="ACK(509850.4,"
 G RE:'D S DQ=2 G 2
C1 G C1S:$D(DE(1))[0 K DB
 S X=DE(1),DIC=DIE
 K ^ACK(509850.6,DA(1),3,"B",$E(X,1,30),DA)
 S X=DE(1),DIC=DIE
 X "D SEND^ACKQUTL5(DA(1))"
 S X=DE(1),DIC=DIE
 X "D KILLEC^ACKQUTL5(DA,DA(1))"
C1S S X="" G:DG(DQ)=X C1F1 K DB
 S X=DG(DQ),DIC=DIE
 S ^ACK(509850.6,DA(1),3,"B",$E(X,1,30),DA)=""
 S X=DG(DQ),DIC=DIE
 X "D SEND^ACKQUTL5(DA(1))"
 S X=DG(DQ),DIC=DIE
 ;
C1F1 Q
X1 S DIC("S")="I $D(ACKCSC),'$G(ACKEVENT),$$CPT^ACKQUT1(+Y,ACKVD,ACKCSC)" S DIC("W")="" D ^DIC K DIC S DIC=DIE,X=+Y K:Y<0 X
 Q
 ;
2 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=2 D X2 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X2 S ACKPC=X
 Q
3 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=3 D X3 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X3 D LONG^ACKQUTL6(ACKPC,"")
 Q
4 D:$D(DG)>9 F^DIE17,DE S DQ=4,D=0 K DE(1) ;.04
 S DIFLD=.04,DGO="^ACKQTE11",DC="1^509850.64PA^1^",DV="509850.64M*P509850.5'X",DW="0;1",DOW="CPT MODIFIER",DLB=$P($$EZBLD^DIALOG(8042,DOW),": ") S:D DC=DC_D
 S DU="ACK(509850.5,"
 G RE:D I $D(DSC(509850.64))#2,$P(DSC(509850.64),"I $D(^UTILITY(",1)="" X DSC(509850.64) S D=$O(^(0)) S:D="" D=-1 G M4
 S D=$S($D(^ACK(509850.6,D0,3,DA,1,0)):$P(^(0),U,3,4),$O(^(0))'="":$O(^(0)),1:-1)
M4 I D>0 S DC=DC_D I $D(^ACK(509850.6,D0,3,DA,1,+D,0)) S DE(4)=$P(^(0),U,1)
 G RE
R4 D DE
 S D=$S($D(^ACK(509850.6,D0,3,DA,1,0)):$P(^(0),U,3,4),1:1) G 4+1
 ;
5 S DQ=6 ;@360
6 S DW="0;3",DV="RNJ2,0",DU="",DLB="VOLUME",DIFLD=.03
 S DE(DW)="C6^ACKQTE9"
 S X=1
 S Y=X
 G Y
C6 G C6S:$D(DE(6))[0 K DB
 S X=DE(6),DIC=DIE
 X "D SEND^ACKQUTL5(DA(1))"
 S X=DE(6),DIC=DIE
 X "D CPVOLPRV^ACKQUTL5(DA,DA(1),X,""V"",""D"")"
C6S S X="" G:DG(DQ)=X C6F1 K DB
 S X=DG(DQ),DIC=DIE
 X "D SEND^ACKQUTL5(DA(1))"
 S X=DG(DQ),DIC=DIE
 X "D CPVOLPRV^ACKQUTL5(DA,DA(1),X,""V"",""S"")"
C6F1 Q
X6 K:+X'=X!(X>99)!(X<1)!(X?.E1"."1N.N) X
 Q
 ;
7 S DQ=8 ;@363
8 D:$D(DG)>9 F^DIE17,DE S DQ=8,DW="0;4",DV="*P509850.3'",DU="",DLB="PROCEDURE PROVIDER",DIFLD=.05
 S DE(DW)="C8^ACKQTE9"
 S DU="ACK(509850.3,"
 S X=$$GET1^DIQ(509850.6,ACKVIEN_",",6)
 S Y=X
 G Y
C8 G C8S:$D(DE(8))[0 K DB
 S X=DE(8),DIC=DIE
 X "D SEND^ACKQUTL5(DA(1))"
 S X=DE(8),DIC=DIE
 X "D CPVOLPRV^ACKQUTL5(DA,DA(1),X,""P"",""D"")"
C8S S X="" G:DG(DQ)=X C8F1 K DB
 S X=DG(DQ),DIC=DIE
 X "D SEND^ACKQUTL5(DA(1))"
 S X=DG(DQ),DIC=DIE
 X "D CPVOLPRV^ACKQUTL5(DA,DA(1),X,""P"",""S"")"
C8F1 Q
X8 S DIC("S")="I $D(ACKVD) S ACKVALSC=$$STACT^ACKQUTL(+Y,ACKVD) I ACKVALSC=""0""!(ACKVALSC=""-6"")" D ^DIC K DIC S DIC=DIE,X=+Y K:Y<0 X
 Q
 ;
9 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=9 D X9 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X9 I X="" W !,"Each Procedure must have a Provider allocated.",! S Y="@363"
 Q
10 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=10 D X10 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X10 D ADDPROV^ACKQUTL(ACKVIEN,X)
 Q
11 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=11 D X11 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X11 K ACKPC
 Q
12 S DQ=13 ;@365
13 G 1^DIE17
