VIABRPC ;AAC/JMC - VIA RPCs ;04/05/2016
 ;;1.0;VISTA INTEGRATION ADAPTER;**7,8**;06-FEB-2014;Build 8
 ; ICR 10090    INSTITUTION FILE (Supported)
 ; ICR 3213     XQALSURO (Supported)
 ; ICR 2533     DBIA2533 (Controlled)
 ; ICR 10061    VADPT (Supported)
 ; ICR 4807     API FOR RATED DISABILITIES [D ELIG^VADPT] (Supported)
 ; ICR 3119     Consult Default Reason for Request [GETDEF^GMRCDRFR & $$REAF^GMRCDRFR]
 ; ICR 2968     Direct access to file 34
 ; ICR 2664     OBSERVATION API [$$PT^DGPMOBS] (Supported)
 ; ICR 1995     CPT Code APIs [CODM^ICPTCOD] (Supported)
 ; ICR 3459     PSB MEDICATION HISTORY REPORT [HISTORY^PSBMLHS] (supported)
 ; ICR 1365     DBIA1365 [DSELECT^GMPLENFM] (controlled)
 ; ICR 4075     OR CALL TO TIUSRVP [VSTRBLD^TIUSRVP] (private)
 ;
GETSURR(RESULT,USER) ; surrogate info.
 ;RPC VIAB GETSURR
 ; get user's surrogate info
 I $G(USER)="" S RESULT="" Q
 S RESULT=$$GETSURO^XQALSURO(USER) ;ICR(DBIA) #3213 
 I +RESULT<1 S RESULT=""
 Q
SNAME(RET,SID) ; get station/site name
 ;RPC VIAB SITENAME
 N SIEN
 I $G(SID)="" S RET="-1^Missing Station Number or Site ID" Q
 S SIEN=$O(^DIC(4,"D",SID,0)) I 'SIEN S RET="-1^No site found for this Station Number or Site ID" Q
 ; ICR(DBIA) #10090 (SUPPORTED)
 S RET=$$GET1^DIQ(4,SIEN,.01,"E")
 Q
USERDIV(RESULT,VIADUZ) ; station IEN^station number^station name^default division
 ;RPC GET USER DIVISIONS
 K RESULT
 N VIADX,VIADR,VIADC
 S VIADC=0
 D DIV4^XUSER(.VIADR,VIADUZ)
 S VIADX=0
 F  S VIADX=$O(VIADR(VIADX)) Q:'VIADX!($D(RESULT(1)))  D
 .I VIADR(VIADX)=1 S VIADC=VIADC+1,RESULT(VIADC)=VIADX_"^"_$$GET1^DIQ(4,+VIADX,99)_"^"_$$GET1^DIQ(4,+VIADX,.01,)_"^1" K VIADR(VIADX)
 S VIADX=0
 F  S VIADX=$O(VIADR(VIADX)) Q:'VIADX  D
 .S VIADC=VIADC+1
 .S RESULT(VIADC)=VIADX_"^"_$$GET1^DIQ(4,+VIADX,99)_"^"_$$GET1^DIQ(4,+VIADX,.01)_"^0"
 Q
 ;
DEFRFREQ(RESULT,VIAIEN,VIADFN,RESOLVE) ;Return default reason for request for service - ICR #3119
 ;RPC VIAB DEFAULT REQUEST REASON
 ; VIAIEN=pointer to file 123.5
 ; VIADFN=patient, if RESOLVE=1
 ; RESOLVE=1 to resolve boilerplate, 0 to not resolve
 Q:+$G(VIAIEN)=0
 I +RESOLVE,(+$G(VIADFN)=0) Q
 S RESULT=$NA(^TMP("VIABREQ",$J))
 S:$G(RESOLVE)="" RESOLVE=0
 D GETDEF^GMRCDRFR(.RESULT,VIAIEN,VIADFN,RESOLVE)
 K @RESULT@(0)
 Q
 ;
EDITDRFR(RESULT,VIAIEN) ; Allow editing of reason for request? - ICR #3119
 ;RPC VIAB EDIT DEFAULT REASON
 S RESULT=$$REAF^GMRCDRFR(VIAIEN)
 Q
 ;
RADSRC(RESULT,SRCTYPE) ; return list of available contract/sharing/research sources - ICR #2968
 ;RPC VIAB RADSRC
 N VIAX
 S VIAX=0
 F I=1:1 S VIAX=$O(^DIC(34,VIAX)) Q:+VIAX=0  D
 . Q:($P(^DIC(34,VIAX,0),U,2)'=SRCTYPE)
 . I $D(^DIC(34,VIAX,"I")),(^DIC(34,VIAX,"I")<$$NOW^XLFDT) Q
 . S RESULT(I)=VIAX_U_$P(^DIC(34,VIAX,0),U,1)
 Q
 ;
CURSPE(RESULT,PTDFN) ; Return current treating specialty - ICR #2664
 ;RPC VIAB CURSPE
 Q:'PTDFN
 N SPEC S SPEC=$$PT^DGPMOBS(PTDFN),RESULT=""
 I SPEC'<0 S RESULT=$P(SPEC,U,3)_U_$P(SPEC,U,2)_U_$P(SPEC,U) ;name^ien^obs flag
 Q
 ;
CPTMODS(RESULT,VIACPTCOD,VIADATE) ;Return CPT Modifiers for a CPT Code - ICR #1995
 ;RPC VIAB CPTMODS
 N VIAM,VIAIDX,VIAI,MODNAME
 S:'+$G(VIADATE) VIADATE=DT
 I +($$CODM^ICPTCOD(VIACPTCOD,$NA(VIAM),0,VIADATE)),+$D(VIAM) D
 . S VIAIDX="",VIAI=0
 . F  S VIAIDX=$O(VIAM(VIAIDX)) Q:(VIAIDX="")  D
 . . S VIAI=VIAI+1,MODNAME=$P(VIAM(VIAIDX),U,1)
 . . S RESULT(MODNAME_VIAI)=$P(VIAM(VIAIDX),U,2)_U_MODNAME_U_VIAIDX
 Q
 ;
ACTPROB(RESULT,DFN,VIADATE) ;get list of patient's active problems - ICR #1365
 ;RPC VIAB ACTPROB
 N VIAPROB,VIAPROBIX,VIAPRCNT,GMPINDT,VIAIMPDT
 K ^TMP("IB",$J,"INTERFACES","GMP SELECT PATIENT ACTIVE PROBLEMS")
 S:'+$G(VIADATE) VIADATE=DT
 S GMPINDT=VIADATE,VIAIMPDT=$$IMPDATE^LEXU("10D")
 D DSELECT^GMPLENFM  ;DBIA 1365
 S VIAPRCNT=0
 S VIAPROBIX=0
 F  S VIAPROBIX=$O(^TMP("IB",$J,"INTERFACES","GMP SELECT PATIENT ACTIVE PROBLEMS",VIAPROBIX)) Q:'VIAPROBIX  D  ;DBIA 1365
 . I (VIADATE<VIAIMPDT)&($P(^TMP("IB",$J,"INTERFACES","GMP SELECT PATIENT ACTIVE PROBLEMS",VIAPROBIX),"^",14)="10D") K ^TMP("IB",$J,"INTERFACES","GMP SELECT PATIENT ACTIVE PROBLEMS",VIAPROBIX) Q
 . S VIAPROB=$P(^TMP("IB",$J,"INTERFACES","GMP SELECT PATIENT ACTIVE PROBLEMS",VIAPROBIX),"^",2,3)
 . I $L(VIAPROB)>255 S $P(VIAPROB,U)=$E($P(VIAPROB,U),1,245)
 . I $E(VIAPROB,1)="$" S VIAPROB=$E(VIAPROB,2,255)
 . I '$D(VIAPROB(VIAPROB)) D
 .. S VIAPROB(VIAPROB)=""
 .. S VIAPRCNT=VIAPRCNT+1
 .. S $P(^TMP("IB",$J,"INTERFACES","GMP SELECT PATIENT ACTIVE PROBLEMS",VIAPROBIX),"^",2,3)=VIAPROB
 . E  K ^TMP("IB",$J,"INTERFACES","GMP SELECT PATIENT ACTIVE PROBLEMS",VIAPROBIX)
 S ^TMP("IB",$J,"INTERFACES","GMP SELECT PATIENT ACTIVE PROBLEMS",0)=VIAPRCNT
 S RESULT=$NA(^TMP("IB",$J,"INTERFACES","GMP SELECT PATIENT ACTIVE PROBLEMS"))
 Q
 ;
NOTEVSTR(RESULT,IEN) ; return the VSTR^AUTHOR for a note -; ICR#4075
 ;RPC VIAB NOTEVSTR
 N X0,X12,VISIT
 S X0=$G(^TIU(8925,+IEN,0)),X12=$G(^(12)),VISIT=$P(X12,U,7)
 I +VISIT S RESULT=$$VSTRBLD^TIUSRVP(VISIT) I 1
 E  S RESULT=$P(X12,U,11)_";"_$P(X0,U,7)_";"_$P(X0,U,13)
 Q
 ;
