ICPT65PT ;ALB/ABR - CORRECT SHORT DESCRIPTIONS - 1999 ;   MARCH 2 1999
 ;;6.0;CPT/HCPCS;**5**;May 19, 1997
 ;
 ;  Post-install to correct specified short names in CPT (#81) file 
 ;
EN ;
 N ICPTI,ICPTX,DIE,DR,DA,ERR
 S DIE="^ICPT("
 F ICPTI=1:1 S ICPTX=$P($T(CPTSN+ICPTI),";;",2) Q:ICPTX["$END"  D  Q:$D(ERR)
 . S DA=+ICPTX,DR="2///"_$P(ICPTX,U,2)
 . I '$D(^ICPT(DA,0)) S ERR="CHECK CPT GLOBAL.  UNABLE TO UPDATE" Q
 . D ^DIE
 ;
 I $D(ERR) D BMES^XPDUTL(ERR)
 Q
 ;
CPTSN ;
 ;;64623^INJECT, TX OF NERVE ADD-ON
 ;;82544^COLUMN CHROMOTOGRAPH/ISOTOPE
 ;;$END
