NURSCPU1 ;HIRMFO/RM-NURSING CARE PLAN UTILITIES (cont.) ;2/25/89
 ;;4.0;NURSING SERVICE;**1**;Apr 25, 1997
 ; THIS HAS BEEN INCLUDED AS A FIX SINCE NURSING CARE PLAN DATA IN
 ; THE AGGREGATE TERM FILE REFERENCES THESE ENTRY POINTS
EN1 ;
 G EN1^NURCCPU1
EN2 ;
 G EN2^NURCCPU1
EN3 ;
 G EN3^NURCCPU1
EN4 ;
 G EN4^NURCCPU1
