ABSVNOM ;VAMC ALTOONA/CTB - NATIONAL OFFICIALS MENU REPORTS ;1/11/01  10:20 AM
V ;;4.0;VOLUNTARY TIMEKEEPING;**18,22,23**;JULY 6, 1994
AJR ;List by Annual Joint View Review Month
 N DIC,D0,L,BY,FLDS
 S DIC="^ABS(503334.1,",L=0,(BY,FLDS)="[ABSV AJR REPORT]" D EN1^DIP
 QUIT
CERT ;List of Certifying Officials
 N DIC,D0,L,BY,FLDS
 S DIC="^ABS(503334.1,",L=0,FR=1,TO=1,(BY,FLDS)="[ABSV CERTIFYING OFFICIAL]" D EN1^DIP
 QUIT
VIEW ;View/Print Individual Record
 N DIC,FR,TO,BY,FLDS,X,Y,DX,D0,DA,DISYS,DK,S
 S DIC="^ABS(503334.1,",DIC(0)="AEMNZ" D ^DIC Q:+Y<0
 S (FR,TO)=+Y,L=0,BY="[ABSV NOM VIEW]",FLDS="[CAPTIONED]" D EN1^DIP QUIT
AFFIL ;Print affiliated organizations
 N DIC,D0,L,BY,FLDS
 D ^ABSVSITE Q:'%
 S DIS(0)="I $$AFFIL^ABSVLBL1(D0,"_ABSV("INST")_","_""""_ABSV("SITE")_""""_")"
 S (BY,FLDS)="[ABSV NOM BY ORGANIZATION]",DIC="^ABS(503334.1,",L=0 D EN1^DIP
 QUIT
ALLORG ;Print all organizations
 N DIC,D0,L,BY,FLDS
 S (BY,FLDS)="[ABSV NOM BY ORGANIZATION]",DIC="^ABS(503334.1,",L=0 D EN1^DIP
 QUIT
 QUIT
