ICD1848P ;ALB/MJB - GROUPER UPDATES;11/9/07 1:17pm
 ;;18.0;DRG Grouper;**48**;Oct 13,2000;Build 17
 ;
 Q
EN ; START UPDATE
 ;D DRG^ICD1848A ;YEARLY CHANGES FOR DRGS
 ;D DIAG^ICD1848B ;YEARLY UPDATES FOR NEW DIAGNOSIS CODES
 ;D PRO^ICD1848C ;YEARLY UPDATES FOR NEW PROCEDURE CODES
 ;D DIAG^ICD1848D ;YEARLY UPDATES TO EXISTING DIAGNOSIS CODES
 ;D PRO^ICD1848E ;YEARLY UPDATES TO EXISTING PROCEDURE CODES
 D ADDID^ICD1848L ; UPDATES IDENTIFIER FIELD FOR DIAGNOSIS CODES
 D ID^ICD1848Y ; UPDATES IDENTIFIER FIELD FOR PROCEDURE CODES
 D NEXT^ICD1848L ; UPDATES MAJOR OR CODE
  ;D INACTDRG^ICD1848O ; INACTIVATE DRGS
 Q
