ONCBPC8A ;HIRMFO/GWB -PCE Study of Cancers of the Urinary Bladder -Print (continued) ;8/15/96
 ;;2.11;ONCOLOGY;**6,11,16**;Mar 07, 1995
IV S TABLE="TABLE IV - FIRST COURSE OF TREATMENT"
 I IOST'?1"C".E W ! I ($Y'<(LIN-4)) D HDR^ONCBPC8
 W !?15,TABLE,! D P Q:EX=U
 S D0=ONCONUM D DFC^ONCOCOM S DOIT=Y
 W !,"DATE OF INITIAL TREATMENT...........: ",DOIT D P Q:EX=U
 W !,"PROTOCOL ELIGIBILITY STATUS.........: ",ONC(165.5,IEN,346) D P Q:EX=U
 W !!,"MANAGING PHYSICIANS:",! D P Q:EX=U
 W !,"  PRIMARY PHYSICIAN.................: ",ONC(165.5,IEN,347) D P Q:EX=U
 W !,"  SECONDARY PHYSICIAN...............: ",ONC(165.5,IEN,348) D P Q:EX=U
 W !!,"SURGERY:",! D P Q:EX=U
 S NCDS=$E(ONC(165.5,IEN,58.1),1,2),NCDSOT=ONC(165.5,IEN,58.1)
 S CDS=$E(ONC(165.5,IEN,58.2),1,2),CDSOT=ONC(165.5,IEN,58.2)
 I (CDS="")!(CDS="00") D
 .S SURG=NCDSOT,SURGDT=ONC(165.5,IEN,58.3)
 I ((CDS'="")&(CDS'="00"))!(NCDS="") D
 .S SURG=CDSOT,SURGDT=ONC(165.5,IEN,50)
 S (SURG1,SURG2)=""
 S LOS=$L(SURG) I LOS<56 S SURG1=SURG G SURG
 S NOP=$L($E(SURG,1,42)," ")
 S SURG1=$P(SURG," ",1,NOP-1),SURG2=$P(SURG," ",NOP,999)
SURG I (SURG1="")!($E(SURG1,1,2)="00") S SURGDT="00/00/0000"
 W !,"  DATE OF SURGERY...................: ",SURGDT D P Q:EX=U
 W !,"  TYPE OF SURGERY...................: ",SURG1 D P Q:EX=U
 W:SURG2'="" !,?41,SURG2 D P Q:EX=U
 W !,"  TUMOR RESECTION DURING TURB.......: ",ONC(165.5,IEN,349) D P Q:EX=U
 W !,"  TYPE OF URINARY DIVERSION.........: ",ONC(165.5,IEN,350) ;D P Q:EX=U
 W !,"  PELVIC LYMPH NODE DISSECTION......: ",ONC(165.5,IEN,351)
 I IOST?1"C".E K DIR S DIR(0)="E" D ^DIR Q:'Y  D HDR^ONCBPC8 W !?15,TABLE_" (continued)"
SC W !!,"  SURGICAL COMPLICATIONS:",! D P Q:EX=U
 W !,"    BLEEDING REQUIRING TRANSFUSION..: ",ONC(165.5,IEN,352) D P Q:EX=U
 W !,"    DEEP VENOUS THROMBOSIS..........: ",ONC(165.5,IEN,353) D P Q:EX=U
 W !,"    MYOCARDIAL INFARCTION/ARRHYTHMIA: ",ONC(165.5,IEN,354) D P Q:EX=U
 W !,"    PELVIC ABSCESS..................: ",ONC(165.5,IEN,355) D P Q:EX=U
 W !,"    PNEUMONIA REQUIRING ANTIBIOTICS.: ",ONC(165.5,IEN,356) D P Q:EX=U
 W !,"    POST-OPERATIVE DEATH (30 DAYS)..: ",ONC(165.5,IEN,357) D P Q:EX=U
 W !,"    PULMONARY EMBOLISM/THROMBOSIS...: ",ONC(165.5,IEN,358) D P Q:EX=U
 W !,"    REOPERATION.....................: ",ONC(165.5,IEN,359) D P Q:EX=U
 W !,"    OTHER...........................: ",ONC(165.5,IEN,360)
 I IOST?1"C".E W ! K DIR S DIR(0)="E" D ^DIR Q:'Y  D HDR^ONCBPC8 W !?15,TABLE_" (continued)"
RT W !!,"RADIATION THERAPY:",! D P Q:EX=U
 W !,"  RADIATION THERAPY.................: ",ONC(165.5,IEN,51.2) D P Q:EX=U
 W !,"  DATE RADIATION THERAPY STARTED....: ",ONC(165.5,IEN,51) D P Q:EX=U
 W !,"  DATE RADIATION THERAPY ENDED......: ",ONC(165.5,IEN,361) D P Q:EX=U
 W !,"  TOTAL RAD (cGy/rad) DOSE..........: ",ONC(165.5,IEN,362) D P Q:EX=U
 W !,"  REGIONAL TREATMENT MODALITY.......: ",ONC(165.5,IEN,363) D P Q:EX=U
 W !!,"  RADIATION COMPLICATIONS:",! D P Q:EX=U
 W !,"    URINARY INCONTINENCE............: ",ONC(165.5,IEN,364) D P Q:EX=U
 W !,"    HEMATURIA.......................: ",ONC(165.5,IEN,365) D P Q:EX=U
 W !,"    RADIATION BOWEL INJURY..........: ",ONC(165.5,IEN,366) D P Q:EX=U
 W ! D P Q:EX=U
 W !,"CHEMOTHERAPY:",! D P Q:EX=U
 W !,"  CHEMOTHERAPY......................: ",ONC(165.5,IEN,53.2) D P Q:EX=U
 W !,"  DATE CHEMOTHERAPY STARTED.........: ",ONC(165.5,IEN,53) D P Q:EX=U
 W !,"  DATE CHEMOTHERAPY ENDED...........: ",ONC(165.5,IEN,367) D P Q:EX=U
 W !,"  ROUTE CHEMOTHERAPY ADMINISTERED...: ",ONC(165.5,IEN,368) D P Q:EX=U
 W !!,"  TYPES OF AGENTS ADMINISTERED:",! D P Q:EX=U
 W !,"    ADRIAMYCIN......: ",ONC(165.5,IEN,369),?33,"IFOSFAMIDE......: ",ONC(165.5,IEN,375) D P Q:EX=U
 W !,"    CARBOPLATINUM...: ",ONC(165.5,IEN,370),?33,"METHOTREXATE....: ",ONC(165.5,IEN,376) D P Q:EX=U
 W !,"    CISPLATIN.......: ",ONC(165.5,IEN,371),?33,"TAXOL...........: ",ONC(165.5,IEN,377) D P Q:EX=U
 W !,"    CYCLOPHOSPHAMIDE: ",ONC(165.5,IEN,372),?33,"THIOTEPA........: ",ONC(165.5,IEN,378) D P Q:EX=U
 W !,"    5-FLUOROURACIL..: ",ONC(165.5,IEN,373),?33,"VINBLASTINE.....: ",ONC(165.5,IEN,379) ;D P Q:EX=U
 W !,"    GALLIUM NITRATE.: ",ONC(165.5,IEN,374),?33,"OTHER...........: ",ONC(165.5,IEN,380)
 I IOST?1"C".E K DIR S DIR(0)="E" D ^DIR Q:'Y  D HDR^ONCBPC8 W !?15,TABLE_" (continued)"
IFAOA W !!,"  INDICATION FOR ADMIN OF AGENTS...: ",ONC(165.5,IEN,381) D P Q:EX=U
 W !,"  REASON CHEMOTHERAPY STOPPED......: ",ONC(165.5,IEN,382) D P Q:EX=U
 W !!,"IMMUNOTHERAPY:",! D P Q:EX=U
 W !,"  IMMUNOTHERAPY (BRM)...............: ",ONC(165.5,IEN,55.2) D P Q:EX=U
 W !!,"  TYPE OF IMMUNOTHERAPY (BRM):",! D P Q:EX=U
 W !,"    BCG.............................: ",ONC(165.5,IEN,383) D P Q:EX=U
 W !,"    INTERFERON......................: ",ONC(165.5,IEN,384) D P Q:EX=U
 W !,"    INTERLEUKIN-II..................: ",ONC(165.5,IEN,385) D P Q:EX=U
 W !,"    OTHER...........................: ",ONC(165.5,IEN,386)
 I IOST?1"C".E W ! K DIR S DIR(0)="E" D ^DIR Q:'Y  D HDR^ONCBPC8 G V
 D P Q:EX=U
V S TABLE="TABLE V - FIRST RECURRENCE"
 I IOST'?1"C".E W ! I ($Y'<(LIN-4)) D HDR^ONCBPC8
 W !?15,TABLE,! D P Q:EX=U
 W !,"TYPE OF FIRST RECURRENCE............: ",ONC(165.5,IEN,387) D P Q:EX=U
 W !,"DATE OF FIRST RECURRENCE............: ",ONC(165.5,IEN,70) D P Q:EX=U
 W !,"DISTANT SITE OF FIRST RECURRENCE 1..: ",ONC(165.5,IEN,71.1) D P Q:EX=U
 W !,"DISTANT SITE OF FIRST RECURRENCE 2..: ",ONC(165.5,IEN,71.2) D P Q:EX=U
 W !,"DISTANT SITE OF FIRST RECURRENCE 3..: ",ONC(165.5,IEN,71.3) D P Q:EX=U
 I IOST?1"C".E W ! K DIR S DIR(0)="E" D ^DIR Q:'Y  D HDR^ONCBPC8 G VI
 D P Q:EX=U
VI S TABLE="TABLE VI - STATUS AT LAST CONTACT"
 I IOST'?1"C".E W ! I ($Y'<(LIN-4)) D HDR^ONCBPC8
 W !?15,TABLE,! D P Q:EX=U
 S DLC=""
 I $D(^ONCO(160,ONCOPA,"F","B")) S DLC=$O(^ONCO(160,ONCOPA,"F","B",""),-1)
 I DLC'="" S Y=DLC D DATEOT^ONCOPCE S DLC=Y
 W !,"DATE OF LAST CONTACT OR DEATH......: ",DLC
 W !,"VITAL STATUS.......................: ",ONC(160,ONCOPA,15) D P Q:EX=U
 S CS="" I $D(^ONCO(165.5,ONCONUM,"TS","AA")) D
 .S CSDAT=$O(^ONCO(165.5,ONCONUM,"TS","AA",""))
 .S CSIEN=$O(^ONCO(165.5,ONCONUM,"TS","AA",CSDAT,""))
 .S CSPNT=$P(^ONCO(165.5,ONCONUM,"TS",CSIEN,0),U,2)
 .S CS=$P(^ONCO(164.42,CSPNT,0),U,1)
 W !,"CANCER STATUS......................: ",CS
 W !,"COMPLETED BY.......................: ",ONC(165.5,IEN,81) D P Q:EX=U
 W !,"REVIEWED BY CANCER COMMITTEE.......: ",ONC(165.5,IEN,82)
 I IOST?1"C".E W ! K DIR S DIR(0)="E" D ^DIR
KILL ;Kill Variables and Exit
 K %,DIR,DIROUT,DIRUT,DTOUT,DUOUT,LP,FILN,ONCOBL,EX,TXT,X,Y,SCTIEN
 Q
P ;Display Data
 I ($Y'<(LIN-2)) D  Q:EX=U  W !?15,TABLE_" (continued)",!
 .I IOST?1"C".E K DIR S DIR(0)="E" D ^DIR I 'Y S EX=U Q
 .D HDR^ONCBPC8 Q
 Q
